// Code generated by protoc-gen-go. DO NOT EDIT.
// source: superego/profile/v1alpha1/profile.proto

package profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	date "google.golang.org/genproto/googleapis/type/date"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Information about a person merged from various data sources such as the
// authenticated user's contacts and profile data.
//
// Most fields can have multiple items. The items in a field have no
// guaranteed order, but each non-empty field is guaranteed to have exactly
// one field with `metadata.primary` set to true.
type Profile struct {
	// The resource name for the person, assigned by the server.
	// An ASCII string with a max length of 27 characters, in the form of
	// people/{person_id}.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The person's email addresses.
	EmailAddresses []*EmailAddress `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	// The person's names.
	Names []*Name `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	// The person's occupations.
	Occupations []*Occupation `protobuf:"bytes,4,rep,name=occupations,proto3" json:"occupations,omitempty"`
	// The person's past or current organizations.
	Organizations []*Organization `protobuf:"bytes,5,rep,name=organizations,proto3" json:"organizations,omitempty"`
	// The person's phone numbers.
	PhoneNumbers []*PhoneNumber `protobuf:"bytes,6,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	// The person's skils.
	Skills               []*Skill `protobuf:"bytes,7,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Profile) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func (m *Profile) GetNames() []*Name {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Profile) GetOccupations() []*Occupation {
	if m != nil {
		return m.Occupations
	}
	return nil
}

func (m *Profile) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func (m *Profile) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *Profile) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

// A person's email address.
type EmailAddress struct {
	// The email address.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// The type of the email address. The type can be custom or one of these
	// predefined values:
	//  - home
	//  - work
	//  - other
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The display name of the email.
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAddress) Reset()         { *m = EmailAddress{} }
func (m *EmailAddress) String() string { return proto.CompactTextString(m) }
func (*EmailAddress) ProtoMessage()    {}
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{1}
}

func (m *EmailAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddress.Unmarshal(m, b)
}
func (m *EmailAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddress.Marshal(b, m, deterministic)
}
func (m *EmailAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddress.Merge(m, src)
}
func (m *EmailAddress) XXX_Size() int {
	return xxx_messageInfo_EmailAddress.Size(m)
}
func (m *EmailAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddress.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddress proto.InternalMessageInfo

func (m *EmailAddress) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *EmailAddress) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EmailAddress) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

// A person's name. If the name is a mononym, the family name is empty.
type Name struct {
	// Output only. The display name formatted according to the locale
	// specified by the viewer's account or the Accept-Language HTTP header.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The family name.
	FamilyName string `protobuf:"bytes,2,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	// THe given name.
	GivenName string `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	// The middle name(s).
	MiddleName           string   `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{2}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Name) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *Name) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Name) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

// A person's occupation.
type Occupation struct {
	// The occupation; for example, developer.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Occupation) Reset()         { *m = Occupation{} }
func (m *Occupation) String() string { return proto.CompactTextString(m) }
func (*Occupation) ProtoMessage()    {}
func (*Occupation) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{3}
}

func (m *Occupation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Occupation.Unmarshal(m, b)
}
func (m *Occupation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Occupation.Marshal(b, m, deterministic)
}
func (m *Occupation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occupation.Merge(m, src)
}
func (m *Occupation) XXX_Size() int {
	return xxx_messageInfo_Occupation.Size(m)
}
func (m *Occupation) XXX_DiscardUnknown() {
	xxx_messageInfo_Occupation.DiscardUnknown(m)
}

var xxx_messageInfo_Occupation proto.InternalMessageInfo

func (m *Occupation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// A person's past or current organization. Overlapping date ranges are
// permitted.
type Organization struct {
	// The type of the organization. The type can be custom or one of these
	// predefined values:
	//  - work
	//  - school
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The start date when the person joined the organization.
	StartDate *date.Date `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// The end date when the person left the organization.
	EndDate *date.Date `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// True if the organization is the person's current organization; false if
	// the organization is a past organization.
	Current bool `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	// The name of the organization.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// The person's job title at the organization.
	Title string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	// The person's job description at the organization.
	JobDescription       string   `protobuf:"bytes,7,opt,name=job_description,json=jobDescription,proto3" json:"job_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{4}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Organization) GetStartDate() *date.Date {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Organization) GetEndDate() *date.Date {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Organization) GetCurrent() bool {
	if m != nil {
		return m.Current
	}
	return false
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Organization) GetJobDescription() string {
	if m != nil {
		return m.JobDescription
	}
	return ""
}

// A person's phone number.
type PhoneNumber struct {
	// The phone number.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Output only. The canonicalized ITU-T E.164 form of the phone number.
	CanonicalForm string `protobuf:"bytes,2,opt,name=canonical_form,json=canonicalForm,proto3" json:"canonical_form,omitempty"`
	// The type of the phone number. The type can be custom or one of these
	// predefined values:
	//  - home
	//  - work
	//  - mobile
	//  - homeFax
	//  - workFax
	//  - otherFax
	//  - pager
	//  - workMobile
	//  - workPager
	//  - main
	//  - googleVoice
	//  - other
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{5}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *PhoneNumber) GetCanonicalForm() string {
	if m != nil {
		return m.CanonicalForm
	}
	return ""
}

func (m *PhoneNumber) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// A skill that the person has.
type Skill struct {
	// The skill; for example, gRPC.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_78feb22bbba4b486, []int{6}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "superego.profile.v1alpha1.Profile")
	proto.RegisterType((*EmailAddress)(nil), "superego.profile.v1alpha1.EmailAddress")
	proto.RegisterType((*Name)(nil), "superego.profile.v1alpha1.Name")
	proto.RegisterType((*Occupation)(nil), "superego.profile.v1alpha1.Occupation")
	proto.RegisterType((*Organization)(nil), "superego.profile.v1alpha1.Organization")
	proto.RegisterType((*PhoneNumber)(nil), "superego.profile.v1alpha1.PhoneNumber")
	proto.RegisterType((*Skill)(nil), "superego.profile.v1alpha1.Skill")
}

func init() {
	proto.RegisterFile("superego/profile/v1alpha1/profile.proto", fileDescriptor_78feb22bbba4b486)
}

var fileDescriptor_78feb22bbba4b486 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0xb5, 0xdd, 0x7f, 0xed, 0x64, 0xb7, 0x15, 0x16, 0x42, 0x01, 0xa9, 0x6a, 0x09, 0x2a,
	0xed, 0x01, 0x12, 0x5a, 0x84, 0x84, 0xc4, 0x09, 0xd4, 0xd2, 0x03, 0xa2, 0xad, 0xc2, 0x0d, 0x24,
	0x22, 0x6f, 0x32, 0x4d, 0x5d, 0x1c, 0x3b, 0xb2, 0x93, 0x4a, 0xe5, 0x11, 0x78, 0x40, 0x5e, 0x83,
	0x57, 0x40, 0xb6, 0x93, 0xdd, 0x00, 0xdd, 0xe5, 0x96, 0xf9, 0xf2, 0x9b, 0xf1, 0x7c, 0x9e, 0x49,
	0x60, 0x5f, 0xd7, 0x25, 0x2a, 0xcc, 0x65, 0x54, 0x2a, 0x79, 0xc9, 0x38, 0x46, 0x37, 0x87, 0x94,
	0x97, 0x57, 0xf4, 0xb0, 0x15, 0xc2, 0x52, 0xc9, 0x4a, 0x92, 0x87, 0x2d, 0x18, 0xb6, 0x7a, 0x0b,
	0x3e, 0x7a, 0x90, 0x4b, 0x99, 0x73, 0x8c, 0xaa, 0xdb, 0x12, 0xa3, 0x8c, 0x56, 0x4d, 0x4a, 0xf0,
	0xb3, 0x0f, 0xe3, 0x0b, 0x07, 0x93, 0x27, 0x30, 0x55, 0xa8, 0x65, 0xad, 0x52, 0x4c, 0x04, 0x2d,
	0xd0, 0xef, 0xed, 0xf6, 0x0e, 0x36, 0xe2, 0x49, 0x2b, 0x9e, 0xd1, 0x02, 0xc9, 0x05, 0x6c, 0x61,
	0x41, 0x19, 0x4f, 0x68, 0x96, 0x29, 0xd4, 0x1a, 0xb5, 0xbf, 0xb6, 0xdb, 0x3f, 0xf0, 0x8e, 0xf6,
	0xc3, 0xa5, 0xa7, 0x87, 0x27, 0x26, 0xe3, 0xad, 0x4b, 0x88, 0x37, 0xb1, 0x13, 0xa1, 0x26, 0xaf,
	0x60, 0x68, 0x4e, 0xd3, 0x7e, 0xdf, 0xd6, 0xd9, 0x59, 0x51, 0xc7, 0x74, 0x10, 0x3b, 0x9a, 0x9c,
	0x82, 0x27, 0xd3, 0xb4, 0x2e, 0x69, 0xc5, 0xa4, 0xd0, 0xfe, 0xc0, 0x26, 0xef, 0xad, 0x48, 0x3e,
	0x9f, 0xd3, 0x71, 0x37, 0x93, 0x7c, 0x84, 0xa9, 0x54, 0x39, 0x15, 0xec, 0x7b, 0x53, 0x6a, 0xf8,
	0x5f, 0x3f, 0xe7, 0x1d, 0x3e, 0xfe, 0x33, 0x9b, 0x7c, 0x80, 0x69, 0x79, 0x25, 0x05, 0x26, 0xa2,
	0x2e, 0x66, 0xa8, 0xb4, 0x3f, 0xb2, 0xe5, 0x9e, 0xae, 0x28, 0x77, 0x61, 0xf8, 0x33, 0x8b, 0xc7,
	0x93, 0x72, 0x11, 0x68, 0xf2, 0x1a, 0x46, 0xfa, 0x1b, 0xe3, 0x5c, 0xfb, 0x63, 0x5b, 0x65, 0x77,
	0x45, 0x95, 0x4f, 0x06, 0x8c, 0x1b, 0x3e, 0xf8, 0x02, 0x93, 0xee, 0xad, 0x93, 0xfb, 0x30, 0xbc,
	0xa1, 0xbc, 0x6e, 0x87, 0xea, 0x02, 0x42, 0x60, 0x60, 0x36, 0xc2, 0x5f, 0xb3, 0xa2, 0x7d, 0x26,
	0x8f, 0x61, 0x92, 0x31, 0x5d, 0x72, 0x7a, 0xeb, 0xb6, 0xa0, 0x6f, 0xdf, 0x79, 0x8d, 0x66, 0x46,
	0x10, 0xfc, 0xe8, 0xc1, 0xc0, 0x6e, 0xc3, 0xdf, 0x6c, 0xef, 0x1f, 0x96, 0xec, 0x80, 0x77, 0x49,
	0x0b, 0xc6, 0x1b, 0xc2, 0x9d, 0x04, 0x4e, 0xb2, 0xc0, 0x36, 0x40, 0xce, 0x6e, 0x50, 0x74, 0x4f,
	0xdb, 0xb0, 0x4a, 0x9b, 0x5f, 0xb0, 0x2c, 0xe3, 0xcd, 0x4e, 0x0e, 0x5c, 0xbe, 0x93, 0x6c, 0x33,
	0x01, 0xc0, 0x62, 0xb4, 0x77, 0xfb, 0x0c, 0x7e, 0xf5, 0x60, 0xd2, 0x1d, 0xda, 0xdc, 0x78, 0xaf,
	0x63, 0xfc, 0x05, 0x80, 0xae, 0xa8, 0xaa, 0x12, 0xf3, 0x7d, 0xd8, 0x46, 0xbd, 0xa3, 0x7b, 0xa1,
	0xfb, 0x70, 0x42, 0x43, 0x84, 0xc7, 0xb4, 0xc2, 0x78, 0xc3, 0x42, 0xe6, 0x91, 0x3c, 0x83, 0x75,
	0x14, 0x99, 0xe3, 0xfb, 0xcb, 0xf8, 0x31, 0x8a, 0xcc, 0xd2, 0x3e, 0x8c, 0xd3, 0x5a, 0x29, 0x14,
	0x95, 0x75, 0xb1, 0x1e, 0xb7, 0xa1, 0xe9, 0xc6, 0x9a, 0x1b, 0xba, 0x6e, 0xcc, 0xb3, 0x31, 0x52,
	0xb1, 0x8a, 0xa3, 0x3f, 0x72, 0x46, 0x6c, 0x40, 0xf6, 0x61, 0xeb, 0x5a, 0xce, 0x92, 0x0c, 0x75,
	0xaa, 0x58, 0x69, 0xac, 0xf8, 0x63, 0xfb, 0x7e, 0xf3, 0x5a, 0xce, 0x8e, 0x17, 0x6a, 0xf0, 0x15,
	0xbc, 0xce, 0x5a, 0x2d, 0x19, 0xff, 0x1e, 0x6c, 0xa6, 0x54, 0x48, 0xc1, 0x52, 0xca, 0x93, 0x4b,
	0xa9, 0x8a, 0x66, 0x3c, 0xd3, 0xb9, 0xfa, 0x5e, 0xaa, 0x62, 0x7e, 0x59, 0xfd, 0xc5, 0x65, 0x05,
	0xdb, 0x30, 0xb4, 0x0b, 0x77, 0x77, 0xe5, 0x77, 0xa7, 0x9f, 0x4f, 0x72, 0x56, 0x5d, 0xd5, 0xb3,
	0x30, 0x95, 0x45, 0xd4, 0x2e, 0x2d, 0x2d, 0x99, 0x8e, 0x72, 0xf9, 0x3c, 0x47, 0x61, 0x7f, 0x3f,
	0xd1, 0xd2, 0x3f, 0xdb, 0x9b, 0x46, 0x98, 0x8d, 0x2c, 0xf8, 0xf2, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x50, 0x17, 0x26, 0x41, 0x05, 0x05, 0x00, 0x00,
}
